version: 2
jobs:
 build:
    machine: true
    steps:
      - checkout
      # build the testing image
      - run: docker build -t project .

      # build
      - run: docker run -v $(pwd):/code project bash -c 'cd /code && swift build'

      # unit tests
      - run: docker run -v $(pwd):/code project bash -c 'cd /code && swift test'

      # test CLI
      - run: docker run -v $(pwd):/code project bash -c 'cd /code && .build/debug/Interpolate 20 "s rural" 0.0001 0.0001'
