version: 2
jobs:
 build:
    machine: true
    steps:
      - checkout
      # build the testing image
      - run: docker build -t project .

      # build
      - run: docker run -v $(pwd):/code project bash -c 'cd /code && swift build'

      # unit tests
      - run: docker run -v $(pwd):/code project bash -c 'cd /code && swift test'

      # test CLI
      - run: docker run -v $(pwd):/code project bash -c 'cd /code && export INTERPOLATION_DATA_DIR=/code/Tests/AddressInterpolation.Tests/basic && .build/debug/Interpolate " -41.288788,174.766843" 18 "glasgow street"'
