version: 2
jobs:
 build:
    machine: true
    steps:
      - checkout
      # pull the swift-postal image
      - run: docker pull igormaka/swift-libpostal

      - run: docker run igormaka/swift-libpostal bash -c 'apt-get install libsqlite3-dev'

      # build
      - run: docker run -v $(pwd):/code igormaka/swift-libpostal bash -c 'apt-get install libsqlite3-dev; cd /code && swift build'

      # unit tests
      - run: docker run -v $(pwd):/code igormaka/swift-libpostal bash -c 'cd /code && swift test'

      # test CLI
      - run: docker run -v $(pwd):/code igormaka/swift-libpostal bash -c 'cd /code && .build/debug/Interpolate 20 "s rural" 0.0001 0.0001'
